rules:
  - name: Bug
    keywords:
      - bug
    colors:
      - "d73a4a"
    appliesTo:
      - issues
      - pull_requests

  - name: Enhancement
    keywords:
      - enhancement
    colors:
      - "a2eeef"
    appliesTo:
      - issues
      - pull_requests

  - name: Documentation
    keywords:
      - docs
    colors:
      - "0075ca"
    appliesTo:
      - issues
      - pull_requests
