version: '3.8'
services:
  skywizz:
    image: REPLACE_IMAGE_NAME
    volumes:
      - skywizz-data:/skywizz:rw 
    restart: unless-stopped
    environment:
      CONFIG_VERSION: "${CONFIG_VERSION}"
      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_PREFIX: "${BOT_PREFIX}"
      BOT_STATUS: "${BOT_STATUS}"
      PYTHON_ENV: "${PYTHON_ENV}"
      LOG_LEVEL: "${LOG_LEVEL}"
      TIMEZONE: "${TIMEZONE}"
    networks:
      - skywizz-net

volumes:
  skywizz-data:

networks:
  skywizz-net:
    driver: bridge
