services:
  skywizz:
    image: REPLACE_IMAGE_NAME
    volumes:
      - skywizz-data:/skywizz:rw 
    restart: unless-stopped
    networks:
      - skywizz-net

volumes:
  skywizz-data:

networks:
  skywizz-net:
    driver: bridge
