services:
  skywizz:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - skywizz-data:/skywizz:rw 
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - skywizz-net

volumes:
  skywizz-data:

networks:
  skywizz-net:
    driver: bridge
