version: '3.8'
services:
  skywizz:
    build:
      context: .
    volumes:
      - .:/skywizz:rw
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_PREFIX=${BOT_PREFIX}
      - BOT_STATUS=${BOT_STATUS}
      - CONFIG_VERSION=${CONFIG_VERSION}
volumes:
  skywizz-data: