services:
  bot:
    image: ${BOT_IMAGE}
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      TIMEZONE: ${TIMEZONE:-UTC}
    networks:
      - skywizz-data
    restart: unless-stopped

networks:
  skywizz-data:
    external: true
