# https://github.com/theos/theos/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
name: "🐛 Bug Report"
description: We broke something, again
title: "[Bug]: "
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!** Please make sure you read our [issue guidelines](https://github.com/kreativermario/SkyWizz/blob/master/.github/CONTRIBUTING.md) first, then fill out the fields below.

        If you’re unsure whether the issue you’re having is a bug, you can post in [Discussions](https://github.com/kreativermario/SkyWizz/discussions) instead.

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Install pip requirements
        2. Run `python SkyWizz.py` or `python3 SkyWizz.py`
        3. …
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: Paste any relevant logs, error output, etc.
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        (If it’s long, please paste to https://gist.github.com/ and insert the link here.)
      render: shell

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context you can provide about the problem here.

  - type: textarea
    id: list-dependencies
    attributes:
      label: List of dependencies installed in your python environment
      description: Please copy and paste the python enviroment list of packages and their versions

  - type: markdown
    attributes:
      value: |
        ----
        
        # Details of your host machine (the device you’re running SkyWizz on)

  - type: dropdown
    id: host-os
    attributes:
      label: What OS are you seeing the problem on?
      options:
        - Windows
        - macOS
        - Linux/WSL
        - Other
      multiple: true
    validations:
      required: true

  - type: input
    id: host-os-version
    attributes:
      label: What OS version does it have installed?
      placeholder: "e.g. macOS 11.5.1, Windows 11"
    validations:
      required: true

  - type: input
    id: host-python-version
    attributes:
      label: What Python version are you using on your host machine?
      placeholder: "e.g. Python 3.11.5"
    validations:
      required: true

  - type: input
    id: host-ide
    attributes:
      label: Which IDE or development environment are you using? (please include the version)
      placeholder: "e.g. Visual Studio Code, PyCharm"
    validations:
      required: true